app:
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: url
      target: https://github.com/humanitec-poc-org-8367/backstage/blob/main/catalog-info-v10.yaml
    - type: url
      target: https://github.com/humanitec-poc-org-8367/backstage/blob/main/templates/score-example-v10/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/humanitec-poc-org-8367/backstage/blob/main/templates/podinfo-example-v10/template.yaml
      rules:
        - allow: [Template]
