app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Humanitec

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers: {}

scaffolder:

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../catalog-info-v12.yaml
    - type: file
      target: ../../templates/score-example-v12/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../templates/podinfo-example-v12/template.yaml
      rules:
        - allow: [Template]

humanitec:
  orgId: htc-demo-12
  token: ${HUMANITEC_TOKEN}
  registryUrl: 675957821105.dkr.ecr.us-east-1.amazonaws.com
