name: Deploy ${{ values.name | capitalize }}

on:
  push:
    branches: main

env:
  ECR: ${{ values.registryUrl }}
  IMAGE: ${{ values.image }}

jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-7`" >> $GITHUB_ENV

      - run: |
          aws ecr get-login-password --region eu-west-2 \
            | docker login \
                --username $username \
                --password-stdin \
                ${{ values.registryUrl }}
        env:
          username: ${{ secrets.ECR_USER }}
          password: ${{ secrets.ECR_PASS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: docker build --platform linux/amd64 . -t $ECR/$IMAGE:$TAG
      - run: docker push $ECR/$IMAGE:$TAG

# notify humanitec