name: Deploy Backstage

on:
  push:
    branches: main

concurrency: ${{ github.ref }}

env:
  IMAGE: '285565080433.dkr.ecr.eu-west-2.amazonaws.com/backstage'

jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-7`" >> $GITHUB_ENV

      - run: yarn
      - run: yarn tsc
      - run: yarn build:all
      - run: yarn build-image

      - run: docker tag backstage $IMAGE:$TAG
      - run: echo $password | docker login --username "$username" --password-stdin "$registry"
        env:
          registry: ${{ secrets.ECR_REGISTRY }}
          username: ${{ secrets.ECR_USER }}
          password: ${{ secrets.ECR_PASS }}
      - run: docker push $IMAGE:$TAG

      # inform humanitec
        # org_id, humanitec_token
