name: Deploy Backstage

on:
  push:
    branches: main

concurrency: ${{ github.ref }}

env:
  ECR: 285565080433.dkr.ecr.eu-west-2.amazonaws.com
  IMAGE: backstage

jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-7`" >> $GITHUB_ENV

      - run: yarn
      - run: yarn tsc
      - run: yarn build:all
      - run: yarn build-image

      - run: |
          aws ecr get-login-password --region eu-west-2 \
            | docker login \
                --username ${{ secrets.ECR_USER }} \
                --password-stdin \
                $ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: docker tag backstage $ECR/$IMAGE:$TAG
      - run: docker push $ECR/$IMAGE:$TAG

      - name: Inform Humanitec
        run: |-
          curl \
            --request POST 'https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG_ID }}/images/backstage/builds' \
            --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "branch": "'$GITHUB_REF_NAME'",
                "commit": "'$GITHUB_SHA'",
                "image": "'$ECR/$IMAGE:$TAG'",
                "tags": ["'$TAG'"]
            }'